# @package model.indicator_function.mlp

defaults:
  - _self_
  - activation: relu 
  - out_activation: sigmoid

_target_: neural_poisson.model.encoder.MultiLayerPerceptron
_partial_: True
in_features: ???
out_features: 1
hidden_features: 32
num_hidden_layers: 3
activation: ???
out_activation: ???
out_bias: False
weight_init: null
first_layer_weight_init: null