# @package _global_

defaults:
  - model: neural_poisson 
  - encoder: mlp
  - optimizer: adam
  - scheduler: linear
  - logger: wandb
  - data: shapenet
  - trainer: default
  - callbacks: default
  - hydra: default
  - paths: default
  - _self_

# base settings
device: cuda
seed: 123
ckpt_path: Null

# logging settings
task_name: train 
tags: [train]
