# @package model.indicator_function

defaults:
  - base
  - mlp/tiny_relu

encoding:
  _target_: neural_poisson.model.encoder.HashGridEncoding
  _partial_: True
  L: 10
  T: 524288  # 2^19
  F: 2
  N_min: 16
  N_max: 512
  domain: [-1.0, 1.0]
  init_mode: uniform
  activation: relu