# @package model.indicator_function

defaults:
  - base
  - mlp/tiny
  - mlp/activation/relu

encoding:
  _target_: neural_poisson.model.encoding.PositionalEncoding
  _partial_: True
  L: 10
  activation: relu
