# @package model 

_target_: neural_poisson.model.neural_poisson.NeuralPoisson

# module setting
hidden_dim: 512
num_layers: 8

# training settings
optimizer:
  _target_: torch.optim.Adam 
  _partial_: True
  lr: 1e-04
monitor: train/loss
# scheduler: null
scheduler:
  _partial_: True
  _target_: torch.optim.lr_scheduler.LinearLR
  total_iters: 10000 
  start_factor: 1.0
  end_factor: 1e-02

