# @package model 

_target_: neural_poisson.model.neural_poisson.NeuralPoisson

# different hydra groups
encoder: ???
optimizer: ???
scheduler: ???

# network settings
lambda_gradient: 1.0
lambda_surface: 100.0
lambda_empty_space: 100.0

# warmup scheduler
gradient_mode: one  # increase, one
close_mode: one   # increase, one
indicator_mode: zero  # decrease, zero
gradient_steps: 100
close_steps: 100
indicator_steps: 100

# indicator settings
indicator_function: center  # default, center
activation: sigmoid  # sin, sigmoid

# logging
log_camera_idxs: ${data.dataset.log_camera_idxs}
log_metrics: True
log_images: True
log_optimizer: True
log_mesh: True
log_metrics_every_n_steps: 10
log_images_every_n_steps: ${data.epoch_size}
log_optimizer_every_n_steps: ${data.epoch_size}
log_mesh_every_n_epochs: 10

# metrics
num_points_chamfer: 100_000

# marching cubes
voxel_size: 256
domain: ${data.dataset.domain}
chunk_size: 10_000
